name: Run Behave Tests

permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - feature/rajesh-CBATest
      - main
  pull_request:
    branches:
      - main

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure

      - name: Run Behave Tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter --junit --junit-directory reports -o allure-results

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: behave-junit-report
          path: reports

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/TESTS-*.xml'

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report